version: "3"

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:alpine3.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgresData:/var/lib/postgresql/data
    
volumes:
  postgresData: